name: OneHHOneHH
version: '1.3.0'
main: me.gonkas.onehhonehh.OneHHOneHH
api-version: '1.20'
authors: [Gonkas77]
description: "100 Hearts 100 Hours plugin. Essentially your objective is to survive 100 Hours before you lose 100 Hearts of damage."
commands:
  sethp:
    permission: onehhonehh.admin
    permission-message: "ยง4Only Admins can run this command!"
  gethp:
    default: true
  syntax:
    default: true
  timer:
    default: true
  toggle:
    default: true